DROP PROCEDURE IF EXISTS `?`;
DELIMITER //
CREATE PROCEDURE `?`()
BEGIN
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION BEGIN END;
  ALTER TABLE `item_loot_items` ADD COLUMN `item_index` int(10) unsigned NOT NULL DEFAULT '0' AFTER `item_count`;
END //
DELIMITER ;
CALL `?`();
DROP PROCEDURE `?`;
