/**
* -- WOW FREEDOM COMMAND TRINITY STIRNGS --
* Description: main SQL script to add trinity strings used by Freedom commands to TrinityCore
*/


-- Colors and color closure
SET @C_TITLE := '|cffd2691e';
SET @C_LINK := '|cffff4500';
SET @C_TEXT := '|cffbbbbbb';
SET @C_ERR := '|cffff0000';
SET @C_CLOSE := '|r'; -- stops/closes color tag

-- Templates
SET @T_CMD_INFO := CONCAT(@C_TITLE, '>> ', @C_CLOSE);
SET @T_CMD_SYNTAX := CONCAT(@C_TITLE, 'SYNTAX: ', @C_CLOSE);
SET @T_CMD_ERROR := CONCAT(@C_ERR, 'ERROR: ', @C_CLOSE);
SET @T_GLOBAL_GM := CONCAT(@C_LINK, '[GM-NOTIFY] ', @C_CLOSE);
SET @T_GLOBAL    := CONCAT(@C_LINK, '[GLOBAL NOTIFY] ', @C_CLOSE);

REPLACE INTO trinity_string (entry, content_default) VALUES
/* FREEDOM_CMDE_NOT_YET_IMPLEMENTED                         */ (100000, CONCAT(@T_CMD_ERROR, @C_TEXT, 'This command isn\'t implemented yet.', @C_CLOSE)),
/* FREEDOM_CMDI_MONEY_RESET                                 */ (100001, CONCAT(@T_CMD_INFO, @C_TEXT, 'Your money has been reset.', @C_CLOSE)),
/* FREEDOM_CMDE_NOT_ENOUGH_PARAMS                           */ (100002, CONCAT(@T_CMD_ERROR, @C_TEXT, 'Not enough parameters.', @C_CLOSE)),
/* FREEDOM_CMDH_GOTO_RELATIVE                               */ (100003, CONCAT(@T_CMD_SYNTAX, '.goto $local_x [$local_y [$local_z [$local_deg]]]')),
/* FREEDOM_E_INVALID_MAP_COORD                              */ (100004, CONCAT(@T_CMD_ERROR, @C_TEXT, 'Target map or coordinates is invalid (X: %f Y: %f MapId: %u).', @C_CLOSE)),
/* FREEDOM_CMDI_FLAG_FOR_CUSTOMIZATION                      */ (100005, CONCAT(@T_CMD_INFO, @C_TEXT, 'Your character has been successfully flagged for re-customization.', @C_CLOSE)),
/* FREEDOM_CMDI_FLAG_FOR_RACECHANGE                         */ (100006, CONCAT(@T_CMD_INFO, @C_TEXT, 'Your character has been successfully flagged for race change.', @C_CLOSE)),
/* FREEDOM_CMDI_FLAG_FOR_FACTIONCHANGE                      */ (100007, CONCAT(@T_CMD_INFO, @C_TEXT, 'Your character has been successfully flagged for faction change.', @C_CLOSE)),
/* FREEDOM_CMDI_FIX_ITEMS                                   */ (100008, CONCAT(@T_CMD_INFO, @C_TEXT, 'All your character\'s items are repaired.', @C_CLOSE)),
/* FREEDOM_CMDH_WATERWALK                                   */ (100009, CONCAT(@T_CMD_SYNTAX, '.freedom waterwalk on/off')),
/* FREEDOM_CMDI_WATERWALK                                   */ (100010, CONCAT(@T_CMD_INFO, @C_TEXT, 'Waterwalk toggle: ', @C_LINK, '%s', @C_CLOSE)),
/* FREEDOM_CMDH_DRUNK                                       */ (100011, CONCAT(@T_CMD_SYNTAX, '.freedom drunk $drunkPercentage ($drunkPercentage must be between 0 and 100)')),
/* FREEDOM_CMDI_DRUNK                                       */ (100012, CONCAT(@T_CMD_INFO, @C_TEXT, 'Drunkenness level set to ', @C_LINK, '%d%%', @C_CLOSE)),
/* FREEDOM_CMDH_MOD_SPEED                                   */ (100013, CONCAT(@T_CMD_SYNTAX, '.freedom swim/fly/walk/run/speed $speedValue')),
/* FREEDOM_CMDI_MOD_SPEED                                   */ (100014, CONCAT(@T_CMD_INFO, @C_TEXT, 'Movement speed of type ', @C_LINK, '%s', @C_TEXT, ' was set to value ', @C_LINK, '%.2f', @C_CLOSE)),
/* FREEDOM_CMDE_VALUE_OUT_OF_RANGE                          */ (100015, CONCAT(@T_CMD_ERROR, @C_TEXT, 'Given value was out of allowed range (Max: ', @C_LINK, '%.2f', @C_TEXT, ', Min: ', @C_LINK, '%.2f', @C_TEXT, ').', @C_CLOSE)),
/* FREEDOM_CMDH_FLY                                         */ (100016, CONCAT(@T_CMD_SYNTAX, '.freedom fly on/off')),
/* FREEDOM_CMDI_FLY                                         */ (100017, CONCAT(@T_CMD_INFO, @C_TEXT, 'Fly toggle: ', @C_LINK, '%s', @C_CLOSE)),
/* FREEDOM_CMDI_DEMORPH                                     */ (100018, CONCAT(@T_CMD_INFO, @C_TEXT, 'You have been successfully demorphed.', @C_CLOSE)),
/* FREEDOM_CMDH_SCALE                                       */ (100019, CONCAT(@T_CMD_SYNTAX, '.freedom scale $scaleValue')),
/* FREEDOM_CMDI_SCALE                                       */ (100020, CONCAT(@T_CMD_INFO, @C_TEXT, 'You have been scaled to value ', @C_LINK, '%.2f', @C_CLOSE)),
/* FREEDOM_CMDI_UNAURA                                      */ (100021, CONCAT(@T_CMD_INFO, @C_TEXT, 'All auras have been successfully removed from you.', @C_CLOSE)),
/* FREEDOM_CMDI_REVIVE                                      */ (100022, CONCAT(@T_CMD_INFO, @C_TEXT, 'You have successfully crawled back from the dead.', @C_CLOSE)),
/* FREEDOM_CMDE_REVIVE                                      */ (100023, CONCAT(@T_CMD_ERROR, @C_TEXT, 'You are already alive.', @C_CLOSE)),
/* FREEDOM_CMDH_SUMMON                                      */ (100024, CONCAT(@T_CMD_SYNTAX, '.freedom summon $playerName')),
/* FREEDOM_CMDI_SUMMON                                      */ (100025, CONCAT(@T_CMD_INFO, @C_TEXT, 'Summon request sent to player ', @C_LINK, '%s', @C_CLOSE)),
/* FREEDOM_CMDE_SUMMON_NOT_FOUND                            */ (100026, CONCAT(@T_CMD_ERROR, @C_TEXT, 'Player ', @C_LINK, '%s ', @C_TEXT, 'is either offline, currently loading or does not exist.', @C_CLOSE)),
/* FREEDOM_CMDE_SUMMON_IGNORE                               */ (100027, CONCAT(@T_CMD_ERROR, @C_TEXT, 'Player ', @C_LINK, '%s ', @C_TEXT, 'is ignoring you.', @C_CLOSE)),
/* FREEDOM_CMDE_SUMMON_GM_ON                                */ (100028, CONCAT(@T_CMD_ERROR, @C_TEXT, 'Player ', @C_LINK, '%s ', @C_TEXT, 'has GM tag ON.', @C_CLOSE)),
/* FREEDOM_CMDE_SUMMON_EVIL_TWIN                            */ (100029, CONCAT(@T_CMD_ERROR, @C_TEXT, 'Player ', @C_LINK, '%s ', @C_TEXT, 'has Evil Twin aura. Summoning is not possible.', @C_CLOSE)),
/* FREEDOM_CMDI_RELOAD                                      */ (100030, CONCAT(@T_GLOBAL_GM, @C_TEXT, 'FreedomDatabase table ', @C_LINK, '%s', @C_TEXT, ' has been reloaded.', @C_CLOSE)),
/* FREEDOM_CMDI_RELOAD_ALL                                  */ (100031, CONCAT(@T_GLOBAL_GM, @C_TEXT, 'FreedomDatabase tables have been reloaded.', @C_CLOSE)),
/* FREEDOM_CMDI_SEARCH_QUERY_RESULT                         */ (100032, CONCAT(@T_CMD_INFO, @C_TEXT, 'Found total of ', @C_LINK, '%llu', @C_TEXT, ' result(s).', @C_CLOSE)),
/* FREEDOM_CMDE_X_WITH_NAME_NOT_FOUND                       */ (100033, CONCAT(@T_CMD_ERROR, @C_TEXT, '%s with name ', @C_LINK, '%s', @C_TEXT, ' was not found.', @C_CLOSE)),
/* FREEDOM_CMDE_X_WITH_ID_NOT_FOUND                         */ (100034, CONCAT(@T_CMD_ERROR, @C_TEXT, '%s with id ', @C_LINK, '%llu', @C_TEXT, ' was not found.', @C_CLOSE)),
/* FREEDOM_CMDI_X_NONE_FOUND_WITH_NAME                      */ (100035, CONCAT(@T_CMD_INFO, @C_TEXT, 'No %s with name part ', @C_LINK, '%s', @C_TEXT, ' were found.', @C_CLOSE)),
/* FREEDOM_CMDE_X_WITH_NAME_ALREADY_EXISTS                  */ (100036, CONCAT(@T_CMD_ERROR, @C_TEXT, '%s with name ', @C_LINK, '%s', @C_TEXT, ' already exists.', @C_CLOSE)),
/* FREEDOM_CMDE_X_WITH_ID_ALREADY_EXISTS                    */ (100037, CONCAT(@T_CMD_ERROR, @C_TEXT, '%s with id ', @C_LINK, '%llu', @C_TEXT, ' already exists.', @C_CLOSE)),
/* FREEDOM_CMDI_X_ADDED_WITH_NAME                           */ (100038, CONCAT(@T_CMD_INFO, @C_TEXT, '%s successfully added with following name: ', @C_LINK, '%s', @C_CLOSE)),
/* FREEDOM_CMDI_X_WITH_NAME_REMOVED                         */ (100039, CONCAT(@T_CMD_INFO, @C_TEXT, '%s with name ', @C_LINK, '%s', @C_TEXT, ' successfully removed.', @C_CLOSE)),
/* FREEDOM_CMDH_PUBLIC_TELE                                 */ (100040, CONCAT(@T_CMD_SYNTAX, '.freedom teleport $namePart')),
/* FREEDOM_CMDH_PUBLIC_TELE_LIST                            */ (100041, CONCAT(@T_CMD_SYNTAX, '.freedom teleport list $namePart')),
/* FREEDOM_CMDI_PUBLIC_TELE_LIST_ITEM                       */ (100042, CONCAT(@T_CMD_INFO, @C_LINK, '%s', @C_TEXT, ' (Map: ', @C_LINK, '%s', @C_TEXT, ')', @C_CLOSE)),
/* FREEDOM_CMDH_PUBLIC_TELE_ADD                             */ (100043, CONCAT(@T_CMD_SYNTAX, '.freedom teleport add $name')),
/* FREEDOM_CMDH_PUBLIC_TELE_DEL                             */ (100044, CONCAT(@T_CMD_SYNTAX, '.freedom teleport delete $name')),
/* FREEDOM_CMDH_PRIVATE_TELE                                */ (100045, CONCAT(@T_CMD_SYNTAX, '.freedom pteleport $namePart')),
/* FREEDOM_CMDH_PRIVATE_TELE_LIST                           */ (100046, CONCAT(@T_CMD_SYNTAX, '.freedom pteleport list $namePart')),
/* FREEDOM_CMDI_PRIVATE_TELE_LIST_ITEM                      */ (100047, CONCAT(@T_CMD_INFO, @C_LINK, '%s', @C_TEXT, ' (Map: ', @C_LINK, '%s', @C_TEXT, ')', @C_CLOSE)),
/* FREEDOM_CMDH_PRIVATE_TELE_ADD                            */ (100048, CONCAT(@T_CMD_SYNTAX, '.freedom pteleport add $name')),
/* FREEDOM_CMDH_PRIVATE_TELE_DEL                            */ (100049, CONCAT(@T_CMD_SYNTAX, '.freedom pteleport delete $name')),
/* FREEDOM_CMDH_PUBLIC_SPELL                                */ (100050, CONCAT(@T_CMD_SYNTAX, '.freedom spell/cast $spellId/$spellLink')),
/* FREEDOM_CMDH_PUBLIC_SPELL_LIST                           */ (100051, CONCAT(@T_CMD_SYNTAX, '.freedom spell list $namePart')),
/* FREEDOM_CMDI_PUBLIC_SPELL_LIST_ITEM                      */ (100052, CONCAT(@T_CMD_INFO, @C_LINK, '%u', @C_TEXT, ' - %s', @C_CLOSE)),
/* FREEDOM_CMDH_PUBLIC_SPELL_ADD                            */ (100053, CONCAT(@T_CMD_SYNTAX, '.freedom spell add $spellId/$spellLink [true/false (true: allow spell to target others, false: spell only targets caster, by default: false)]')),
/* FREEDOM_CMDH_PUBLIC_SPELL_DEL                            */ (100054, CONCAT(@T_CMD_SYNTAX, '.freedom spell delete $spellId/$spellLink')),
/* FREEDOM_CMDH_MORPH                                       */ (100055, CONCAT(@T_CMD_SYNTAX, '.freedom morph $name/$displayId')),
/* FREEDOM_CMDH_MORPH_LIST                                  */ (100056, CONCAT(@T_CMD_SYNTAX, '.freedom morph list [$namePart]')),
/* FREEDOM_CMDI_MORPH_LIST_ITEM                             */ (100057, CONCAT(@T_CMD_INFO, @C_LINK, '%u', @C_TEXT, ' - ', @C_LINK, '%s', @C_CLOSE)),
/* FREEDOM_CMDH_MORPH_ADD                                   */ (100058, CONCAT(@T_CMD_SYNTAX, '.freedom morph add $name $displayId [$playerName (if not supplied, then add morph to selected player)]')),
/* FREEDOM_CMDH_MORPH_DEL                                   */ (100059, CONCAT(@T_CMD_SYNTAX, '.freedom morph delete $name/$displayId [$playerName (if not supplied, then add morph to selected player)]')),
/* FREEDOM_CMDE_INVALID_SELECTION                           */ (100060, CONCAT(@T_CMD_ERROR, @C_TEXT, 'Invalid selection.', @C_CLOSE)),
/* FREEDOM_CMDI_X_NOT_FOUND                                 */ (100061, CONCAT(@T_CMD_INFO, @C_TEXT, '%s not found.', @C_CLOSE)),
/* FREEDOM_CMDE_INVALID_ARGUMENT_X                          */ (100062, CONCAT(@T_CMD_ERROR, @C_TEXT, 'Invalid argument for: ', @C_CLOSE, '%s')),
/* FREEDOM_CMDI_MORPH                                       */ (100063, CONCAT(@T_CMD_INFO, @C_TEXT, 'Your model display was set to following morph: ', @C_LINK, '%s', @C_TEXT, ' (Display ID: ', @C_LINK, '%u', @C_TEXT, ')', @C_CLOSE)),
/* FREEDOM_CMDI_MORPH_ADD                                   */ (100064, CONCAT(@T_CMD_INFO, @C_TEXT, 'Morph (Name: ', @C_LINK, '%s', @C_TEXT, ', Display ID: ', @C_LINK, '%u', @C_TEXT, ') successfully added to following player: ', @C_LINK, '%s', @C_CLOSE)),
/* FREEDOM_CMDI_MORPH_DEL                                   */ (100065, CONCAT(@T_CMD_INFO, @C_TEXT, 'Morph (Name: ', @C_LINK, '%s', @C_TEXT, ', Display ID: ', @C_LINK, '%u', @C_TEXT, ') successfully removed from following player: ', @C_LINK, '%s', @C_CLOSE)),
/* FREEDOM_CMDI_PUBLIC_SPELL_ADD                            */ (100066, CONCAT(@T_CMD_INFO, @C_TEXT, 'Public spell (Name link: %s, Spell ID: ', @C_LINK, '%u', @C_TEXT, ') successfully added to public spell list.', @C_CLOSE)),
/* FREEDOM_CMDI_PUBLIC_SPELL_DEL                            */ (100067, CONCAT(@T_CMD_INFO, @C_TEXT, 'Public spell (Name link: %s, Spell ID: ', @C_LINK, '%u', @C_TEXT, ') successfully removed from public spell list.', @C_CLOSE)),
/* FREEDOM_CMDH_HOVER                                       */ (100068, CONCAT(@T_CMD_SYNTAX, '.freedom hover on/off')),
/* FREEDOM_CMDI_HOVER                                       */ (100069, CONCAT(@T_CMD_INFO, @C_TEXT, 'Hover toggle: ', @C_LINK, '%s', @C_CLOSE)),
/* FREEDOM_CMDE_SUMMON_PENDING                              */ (100070, CONCAT(@T_CMD_ERROR, @C_TEXT, 'Player ', @C_LINK, '%s ', @C_TEXT, 'already has a pending summon request from someone.', @C_CLOSE)),
/* FREEDOM_CMDE_X_IS_BLACKLISTED                            */ (100071, CONCAT(@T_CMD_ERROR, @C_TEXT, '%s is blacklisted. Only GMs or higher can bypass this.', @C_CLOSE)),
/* FREEDOM_CMDH_BLACKLIST_ITEM                              */ (100072, CONCAT(@T_CMD_SYNTAX, '.blacklist item $itemId/$itemLink [$flag] ($flag = 1 by default)')),
/* FREEDOM_CMDI_BLACKLIST_ITEM                              */ (100073, CONCAT(@T_CMD_INFO, 'Item successfully ', @C_LINK, '%s', @C_CLOSE)),
/* FREEDOM_CMDNOSTYLE_ID_AND_NAME_LIST_ITEM                 */ (100074, '%u - %s'),
/* FREEDOM_CMDI_ID_AND_NAME_LIST_ITEM_BLACKLISTED           */ (100075, CONCAT('%u - %s ', @C_ERR, 'BLACKLISTED', @C_CLOSE)),
/* FREEDOM_CMDE_X_WITH_GUID_NOT_FOUND                       */ (100076, CONCAT(@T_CMD_ERROR, @C_TEXT, '%s with guid ', @C_LINK, '%llu', @C_TEXT, ' was not found.', @C_CLOSE)),
/* FREEDOM_CMDE_GAMEOBJECT_SELECT_ENTRY_ID                  */ (100077, CONCAT(@T_CMD_ERROR, 'Cannot find gameobject template (Entry ID: %u) for selected game object with guid %llu. Contact developers about this!')),
/* FREEDOM_CMDE_GAMEOBJECT_SELECT_NOT_IN_WORLD              */ (100078, CONCAT(@T_CMD_ERROR, 'Cannot find gameobject object instance for selected gameobject with guid %llu (Entry ID: %u). Contact developers about this!')),
/* FREEDOM_CMDI_GAMEOBJECT_SELECT                           */ (100079, CONCAT(@T_CMD_INFO, 'Selected gameobject %s (GUID: %llu, Entry ID: %u, Distance: %.3f yards)')),
/* FREEDOM_CMDI_GAMEOBJECT_ACTIVATED                        */ (100080, CONCAT(@T_CMD_INFO, 'Gameobject %s activated!')),
/* FREEDOM_CMDE_TEMPLATE_DOES_NOT_EXIST                     */ (100081, CONCAT(@T_CMD_ERROR, 'Template (GUID: %llu, Entry ID: %u) cannot be found. Contact developers about this!')),
/* FREEDOM_CMDH_GAMEOBJECT_SPAWN                            */ (100082, CONCAT(@T_CMD_SYNTAX, '.gobject add/spawn [temp] $entryId [$spawnTimeSecs]')),
/* FREEDOM_CMDE_GAMEOBJECT_SPAWN_INVALID_ID                 */ (100083, CONCAT(@T_CMD_ERROR, 'Invalid gameobject entry ID')),
/* FREEDOM_CMDE_GAMEOBJECT_SPAWN_FAIL                       */ (100084, CONCAT(@T_CMD_ERROR, 'Failed to spawn gameobject with entry %u (Invalid data, db fail or instance creation fail).')),
/* FREEDOM_CMDI_GAMEOBJECT_SPAWN                            */ (100085, CONCAT(@T_CMD_INFO, 'Gameobject %s spawned (GUID: %llu, Entry ID: %u)')),
/* FREEDOM_CMDE_GAMEOBJECT_SPAWN_INVALID_DISPLAY            */ (100086, CONCAT(@T_CMD_ERROR, 'Failed to spawn gameobject with entry %u (Invalid display: cannot find display with id %u). Contact developers about this!')),
/* FREEDOM_CMDI_GAMEOBJECT_NEAR                             */ (100087, CONCAT(@T_CMD_INFO, 'Found %u gameobjects in %.3f yards.')),
/* FREEDOM_CMDI_GAMEOBJECT_NEAR_MAX_RESULT_COUNT            */ (100088, CONCAT(@T_CMD_INFO, 'Found %u (Max result count) gameobjects in %.3f yards.')),
/* FREEDOM_CMDE_GAMEOBJECT_GUID_NOT_EXISTS                  */ (100089, CONCAT(@T_CMD_ERROR, 'Gameobject with GUID %llu does not exist!')),
/* FREEDOM_CMDE_GAMEOBJECT_ENTRY_NOT_EXISTS                 */ (100090, CONCAT(@T_CMD_ERROR, 'Gameobject with entry %u does not exist!')),
/* FREEDOM_CMDI_GAMEOBJECT_NEAR_LIST_ITEM                   */ (100091, '%.3f yards - Entry: %u : %s'),
/* FREEDOM_CMDI_GAMEOBJECT_MOVE                             */ (100092, CONCAT(@T_CMD_INFO, 'Gameobject %s (GUID: %llu) moved')),
/* FREEDOM_CMDE_INVALID_TARGET_COORDS                       */ (100093, CONCAT(@T_CMD_ERROR, 'Invalid target coordinates (X: %.4f, Y: %.4f, Z: %.4f, MapID: %u)')),
/* FREEDOM_CMDE_GAMEOBJECT_NOT_FOUND                        */ (100094, CONCAT(@T_CMD_ERROR, 'Gameobject not found!')),
/* FREEDOM_CMDI_GAMEOBJECT_TURNED                           */ (100095, CONCAT(@T_CMD_INFO, 'Gameobject %s (GUID: %llu) turned')),
/* FREEDOM_CMDI_GAMEOBJECT_DELETE                           */ (100096, CONCAT(@T_CMD_INFO, 'Gameobject deleted')),
/* FREEDOM_CMDI_GAMEOBJECT_SET_STATE                        */ (100097, CONCAT(@T_CMD_INFO, 'Gameobject state/type set (Type: %u, State: %u)')),
/* FREEDOM_CMDH_GAMEOBJECT_SET_STATE                        */ (100098, CONCAT(@T_CMD_SYNTAX, '.gobject set state $type $state [$guid]')),
/* FREEDOM_CMDH_GAMEOBJECT_SCALE                            */ (100099, CONCAT(@T_CMD_SYNTAX, '.gobject scale $scale [$guid]')),
/* FREEDOM_CMDI_GAMEOBJECT_SCALE                            */ (100100, CONCAT(@T_CMD_INFO, 'Gameobject scale set to %.5f')),
/* FREEDOM_CMDI_GAMEOBJECT_INFO                             */ (100101, CONCAT(@T_CMD_INFO, 'Gameobject %s information:')),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_GUID_FULL                */ (100102, '> GUID (full): %s'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_GUID                     */ (100103, '> GUID: %llu'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_ENTRY                    */ (100104, '> Entry ID: %u %s'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_DISPLAY_ID               */ (100105, '> Display ID: %u'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_SCRIPT_ID                */ (100106, '> Script ID: %u'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_NAME                     */ (100107, '> Name: %s'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_AI_NAME                  */ (100108, '> AIName: %s'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_PHASEMASK                */ (100109, '> PhaseMask: %u'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_PHASELIST                */ (100110, '> Active phase list (PhaseID - PhaseMask):'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_PHASE_LI                 */ (100111, '  %u - %u'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_POS_X                    */ (100112, '> X: %.6f'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_POS_Y                    */ (100113, '> Y: %.6f'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_POS_Z                    */ (100114, '> Z: %.6f'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_ORIENTATION              */ (100115, '> Orientation: %.6f (Deg: %.2f°)'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_DISTANCE                 */ (100116, '> Distance: %.3f yards'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_SCALE                    */ (100117, '> Scale: %.5f'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_STATE                    */ (100118, '> State: (%u) %s'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_CREATOR_PLAYER           */ (100119, '> Creator player: %s (ID: %llu)'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_CREATOR_ACC              */ (100120, '> Creator account: %s (BnetID: %u)'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_MODIFIER_PLAYER          */ (100121, '> Modifier player: %s (ID: %llu)'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_MODIFIER_ACC             */ (100122, '> Modifier account: %s (BnetID: %u)'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_CREATED                  */ (100123, '> Created: %s'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_MODIFIED                 */ (100124, '> Modified: %s'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_NO_HISTORY               */ (100125, '> [History unavailable/not found]'),
/* FREEDOM_CMDH_GAMEOBJECT_PHASE                            */ (100126, CONCAT(@T_CMD_SYNTAX, '.gobject phase [modifiers] $phaseList')),
/* FREEDOM_CMDI_GAMEOBJECT_PHASE_BITFIELDS                  */ (100127, CONCAT(@T_CMD_INFO, 'Gameobject phase set to following phasemask bit-fields:%s')),
/* FREEDOM_CMDI_GAMEOBJECT_PHASE_PHASEIDS                   */ (100128, CONCAT(@T_CMD_INFO, 'Gameobject phase set to following phaemask PhaseIDs:%s')),
/* FREEDOM_CMDE_GAMEOBJECT_PHASE_NOT_SET                    */ (100129, CONCAT(@T_CMD_ERROR, 'Gameobject phase was not modified (invalid $phaseList elements?).')),
/* FREEDOM_CMDH_MODIFY_PHASE                                */ (100130, CONCAT(@T_CMD_SYNTAX, '.modify phase [modifiers] $phaseList')),
/* FREEDOM_CMDI_MODIFY_PHASE_BITFIELDS                      */ (100131, CONCAT(@T_CMD_INFO, 'Phase modified to following phasemask bit-fields:%s')),
/* FREEDOM_CMDI_MODIFY_PHASE_PHASEIDS                       */ (100132, CONCAT(@T_CMD_INFO, 'Phase modified to following phaemask PhaseIDs:%s')),
/* FREEDOM_CMDE_MODIFY_PHASE_NOT_SET                        */ (100133, CONCAT(@T_CMD_ERROR, 'Phase was not modified (invalid $phaseList elements?)')),
/* FREEDOM_CMDE_CREATURE_NOT_FOUND                          */ (100134, CONCAT(@T_CMD_ERROR, 'Creature not found!')),
/* FREEDOM_CMDE_GAMEOBJECT_IS_BLACKLISTED                   */ (100135, CONCAT(@T_CMD_ERROR, @C_TEXT, 'Gameobject is blacklisted, it cannot be spawned.', @C_CLOSE)),
/* FREEDOM_CMDH_BLACKLIST_GAMEOBJECT                        */ (100136, CONCAT(@T_CMD_SYNTAX, '.blacklist gobject $entryId/$gobjectLink [$flag] ($flag = 1 by default)')),
/* FREEDOM_CMDI_BLACKLIST_GAMEOBJECT                        */ (100137, CONCAT(@T_CMD_INFO, 'Gameobject successfully ', @C_LINK, '%s', @C_CLOSE)),
/* FREEDOM_CMDE_CREATURE_IS_BLACKLISTED                     */ (100138, CONCAT(@T_CMD_ERROR, @C_TEXT, 'Creature is blacklisted, it cannot be spawned.', @C_CLOSE)),
/* FREEDOM_CMDH_BLACKLIST_CREATURE                          */ (100139, CONCAT(@T_CMD_SYNTAX, '.blacklist creature $entryId/$creatureLink [$flag] ($flag = 1 by default)')),
/* FREEDOM_CMDI_BLACKLIST_CREATURE                          */ (100140, CONCAT(@T_CMD_INFO, 'Creature successfully ', @C_LINK, '%s', @C_CLOSE)),
/* FREEDOM_CMDH_NPC_ADD                                     */ (100141, CONCAT(@T_CMD_SYNTAX, '.npc add/spawn $entryId')),
/* FREEDOM_CMDE_NPC_ADD_FAIL                                */ (100142, CONCAT(@T_CMD_ERROR, 'Failed to spawn creature with entry %u (Invalid data, db fail or instance creation fail).')),
/* FREEDOM_CMDI_NPC_ADD                                     */ (100143, CONCAT(@T_CMD_INFO, 'Creature %s spawned (GUID: %llu, Entry ID: %u)')),
/* FREEDOM_CMDH_NPC_ADD_ITEM                                */ (100144, CONCAT(@T_CMD_SYNTAX, '.npc add item $itemId [$maxCount [$incrTime [$extendedCost]]]')),
/* FREEDOM_CMDE_MANUAL_SELECT_CREATURE                      */ (100145, CONCAT(@T_CMD_ERROR, 'You need to select/target a creature by clicking on it (.npc select command will not work)')),
/* FREEDOM_CMDE_INVALID_ITEM_ID                             */ (100146, CONCAT(@T_CMD_ERROR, 'Invalid item id')),
/* FREEDOM_CMDE_INVALID_ITEM_NOT_EXISTS                     */ (100147, CONCAT(@T_CMD_ERROR, 'Item with id %u does not exist')),
/* FREEDOM_CMDI_NPC_ADD_ITEM                                */ (100148, CONCAT(@T_CMD_INFO, 'Item %s added to %s list with maxcount %u and incrtime %u and extendedcost %u)')),
/* FREEDOM_CMDE_NPC_ADD_ITEM_CANNOT_ADD                     */ (100149, CONCAT(@T_CMD_ERROR, 'Cannot add item to vendor (invalid item or vendor cannot accept more)')),
/* FREEDOM_CMDE_NPC_ADD_FORMATION_ALREADY_IN                */ (100150, CONCAT(@T_CMD_ERROR, 'Targeted creature %s is already part of existing formation (FormationID: %llu)')),
/* FREEDOM_CMDI_NPC_ADD_FORMATION                           */ (100151, CONCAT(@T_CMD_INFO, 'Targeted creature %s is added to formation of creature with guid %llu (FormationID: %llu)')),
/* FREEDOM_CMDE_NPC_ADD_FORMATION_LEADER_NOT_FfreedomOUND   */ (100152, CONCAT(@T_CMD_ERROR, 'Leader not found')),
/* FREEDOM_CMDH_CREATURE_PHASE                              */ (100153, CONCAT(@T_CMD_SYNTAX, '.npc set phase [modifiers] $phaseList')),
/* FREEDOM_CMDI_CREATURE_PHASE_BITFIELDS                    */ (100154, CONCAT(@T_CMD_INFO, 'Creature phase set to following phasemask bit-fields:%s')),
/* FREEDOM_CMDI_CREATURE_PHASE_PHASEIDS                     */ (100155, CONCAT(@T_CMD_INFO, 'Creature phase set to following phaemask PhaseIDs:%s')),
/* FREEDOM_CMDE_CREATURE_PHASE_NOT_SET                      */ (100156, CONCAT(@T_CMD_ERROR, 'Creature phase was not modified (invalid $phaseList elements?).')),
/* FREEDOM_CMDE_CREATURE_GUID_NOT_EXISTS                    */ (100157, CONCAT(@T_CMD_ERROR, 'Creature with GUID %llu does not exist!')),
/* FREEDOM_CMDE_CREATURE_ENTRY_NOT_EXISTS                   */ (100158, CONCAT(@T_CMD_ERROR, 'Creature with entry %u does not exist!')),
/* FREEDOM_CMDE_CREATURE_CANNOT_EXECUTE_ON_PETS             */ (100159, CONCAT(@T_CMD_ERROR, 'Command cannot execute on pets')),
/* FREEDOM_CMDH_NPC_SET_SCALE                               */ (100160, CONCAT(@T_CMD_SYNTAX, '.npc set scale $scale [$guid]')),
/* FREEDOM_CMDI_NPC_SET_SCALE                               */ (100161, CONCAT(@T_CMD_INFO, 'Creature scale set to %.3f')),
/* FREEDOM_CMDH_NPC_SET_ALLOWMOVEMENT                       */ (100162, CONCAT(@T_CMD_SYNTAX, '.npc set allowmovement on/off')),
/* FREEDOM_CMDI_NPC_SET_ALLOWMOVEMENT_OFF                   */ (100163, CONCAT(@T_CMD_INFO, 'All creature movement disabled')),
/* FREEDOM_CMDI_NPC_SET_ALLOWMOVEMENT_ON                    */ (100164, CONCAT(@T_CMD_INFO, 'All creature movement enabled')),
/* FREEDOM_CMDH_NPC_SET_ENTRY                               */ (100165, CONCAT(@T_CMD_SYNTAX, '.npc set entry $newEntryId [$guid]')),
/* FREEDOM_CMDI_NPC_SET_ENTRY                               */ (100166, CONCAT(@T_CMD_INFO, 'Creature entry updated')),
/* FREEDOM_CMDE_NPC_SET_ENTRY_FAIL                          */ (100167, CONCAT(@T_CMD_ERROR, 'Creature failed to update (invalid entry id?)')),
/* FREEDOM_CMDH_NPC_SET_LEVEL                               */ (100168, CONCAT(@T_CMD_SYNTAX, '.npc set level $newLevel [$guid]')),
/* FREEDOM_CMDE_NPC_SET_LEVEL_BAD_VALUE                     */ (100169, CONCAT(@T_CMD_ERROR, 'Bad value for $newLevel (must be between %u and %u)')),
/* FREEDOM_CMDI_NPC_SET_LEVEL                               */ (100170, CONCAT(@T_CMD_INFO, 'Creature level set')),
/* FREEDOM_CMDE_CREATURE_CANNOT_BE_PET_OR_TOTEM             */ (100171, CONCAT(@T_CMD_ERROR, 'Creature cannot be pet or totem')),
/* FREEDOM_CMDE_CREATURE_CANNOT_BE_PET                      */ (100172, CONCAT(@T_CMD_ERROR, 'Creature cannot be pet')),
/* FREEDOM_CMDE_CREATURE_CANNOT_BE_TOTEM                    */ (100173, CONCAT(@T_CMD_ERROR, 'Creature cannot be totem')),
/* FREEDOM_CMDI_NPC_DELETE                                  */ (100174, CONCAT(@T_CMD_INFO, 'Creature deleted')),
/* FREEDOM_CMDE_CREATURE_SELECT_ENTRY_ID                    */ (100175, CONCAT(@T_CMD_ERROR, 'Cannot find creature template (Entry ID: %u) for selected creature with guid %llu. Contact developers about this!')),
/* FREEDOM_CMDE_CREATURE_SELECT_NOT_IN_WORLD                */ (100176, CONCAT(@T_CMD_ERROR, 'Cannot find creature object instance for selected creature with guid %llu (Entry ID: %u). Contact developers about this!')),
/* FREEDOM_CMDI_CREATURE_SELECT                             */ (100177, CONCAT(@T_CMD_INFO, 'Selected creature %s (GUID: %llu, Entry ID: %u, Distance: %.3f yards)')),
/* FREEDOM_CMDH_NPC_DELETE_ITEM                             */ (100178, CONCAT(@T_CMD_SYNTAX, '.npc delete item $itemId')),
/* FREEDOM_CMDE_CREATURE_SELECT_VENDOR                      */ (100179, CONCAT(@T_CMD_ERROR, 'You need to select a vendor')),
/* FREEDOM_CMDE_NPC_DELETE_ITEM_NOT_IN_LIST                 */ (100180, CONCAT(@T_CMD_ERROR, 'Item (ID: %u) is not in vendor list')),
/* FREEDOM_CMDI_NPC_DELETE_ITEM                             */ (100181, CONCAT(@T_CMD_INFO, 'Item %s (ID: %u) removed from vendor list')),
/* FREEDOM_CMDH_NPC_SET_FACTION_ID                          */ (100182, CONCAT(@T_CMD_SYNTAX, '.npc set factionid $factionId [$guid] ($factionId = 35 for all-friendly)')),
/* FREEDOM_CMDE_NPC_SET_FACTION_INVALID_ID                  */ (100183, CONCAT(@T_CMD_ERROR, 'Invalid faction id %u')),
/* FREEDOM_CMDI_NPC_SET_FACTION_ID                          */ (100184, CONCAT(@T_CMD_INFO, 'Creature faction set (this will apply to all creatures of this creature entry)')),
/* FREEDOM_CMDH_NPC_SET_FLAG                                */ (100185, CONCAT(@T_CMD_SYNTAX, '.npc set flag $npcFlags [$guid] ($flags is uint64 bitmask)')),
/* FREEDOM_CMDI_NPC_SET_FLAG                                */ (100186, CONCAT(@T_CMD_INFO, 'Creature npc flags set (this will apply to all creatures of this creature entry)')),
/* FREEDOM_CMDH_NPC_SET_DATA                                */ (100187, CONCAT(@T_CMD_SYNTAX, '.npc set data $field $data [$guid]')),
/* FREEDOM_CMDI_NPC_SET_DATA                                */ (100188, CONCAT(@T_CMD_INFO, 'SetData performed on %s (Field: %u, Data: %u, with %s)')),
/* FREEDOM_CMDI_NPC_FOLLOW                                  */ (100189, CONCAT(@T_CMD_INFO, '%s is now following you')),
/* FREEDOM_CMDI_CREATURE_INFO                               */ (100190, CONCAT(@T_CMD_INFO, 'Creature %s information:')),
/* FREEDOM_CMDI_CREATURE_INFO_LI_GUID_FULL                  */ (100191, '> GUID (full): %s'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_GUID                       */ (100192, '> GUID: %llu'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_ENTRY                      */ (100193, '> Entry ID: %u %s'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_DISPLAY_ID                 */ (100194, '> Display ID: %u (Native: %u)'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_PHASELIST                  */ (100195, '> Active phase list (PhaseID - PhaseMask):'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_PHASE_LI                   */ (100196, '  %u - %u'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_POS_X                      */ (100197, '> X: %.6f'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_POS_Y                      */ (100198, '> Y: %.6f'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_POS_Z                      */ (100199, '> Z: %.6f'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_FACTION_ID                 */ (100200, '> Faction ID: %u'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_NAME                       */ (100201, '> Name: %s'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_AI_INFO                    */ (100202, '> AIName: %s'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_PHASEMASK                  */ (100203, '> PhaseMask: %u'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_ORIENTATION                */ (100204, '> Orientation: %.6f'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_DISTANCE                   */ (100205, '> Distance: %.3f yards'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_SCALE                      */ (100206, '> Scale: %.5f'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_CREATOR_PLAYER             */ (100207, '> Creator player: %s (ID: %llu)'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_CREATOR_ACC                */ (100208, '> Creator account: %s (BnetID: %u)'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_MODIFIER_PLAYER            */ (100209, '> Modifier player: %s (ID: %llu)'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_MODIFIER_ACC               */ (100210, '> Modifier account: %s (BnetID: %u)'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_CREATED                    */ (100211, '> Created: %s'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_MODIFIED                   */ (100212, '> Modified: %s'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_NO_HISTORY                 */ (100213, '> [History unavailable/not found]'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_SCRIPT_INFO                */ (100214, '> ScriptName: %s'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_FLAGSE_LIST                */ (100215, '> FlagsExtra: %llu, active list:'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_FLAGSE_LI                  */ (100216, '  %s (0x%X)'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_NPCFLAGS_LIST              */ (100217, '> NpcFlags: %llu, active list:'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_MECHANICIMM_LIST           */ (100218, '> MechanicImmune: %u, active list:'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_MECHANICIMM_LI             */ (100219, '  %s (0x%X)'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_UNITFLAGS_LIST             */ (100220, '> UnitFieldFlags: %u, active list:'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_UNITFLAGS_LI               */ (100221, '  %s (0x%X)'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_LEVEL                      */ (100222, '> Level: %u'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_EQUIPMENT                  */ (100223, '> EquipmentId: %u (Original: %u))'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_HEALTH                     */ (100224, '> Health: %u (Max: %u, OnCreation: %u)'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_INHABIT_TYPE               */ (100225, '> InhabitType: %u'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_UNITFLAGS2                 */ (100226, '> UnitFlags2: %u'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_DYNFLAGS                   */ (100227, '> DynamicFlags: %u'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_FACTION_TEMPLATE           */ (100228, '> FactionTemplate: %u'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_RESPAWN_TIMES              */ (100229, '> SpawnTime: Full:%s Remaining:%s'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_LOOT                       */ (100230, '> Loot: %u Pickpocket: %u Skinning: %u'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_DUNGEON_ID                 */ (100231, '> InstanceID: %u'),
/* FREEDOM_CMDI_CREATURE_INFO_LI_ARMOR                      */ (100232, '> Armor: %u'),
/* FREEDOM_CMDI_NPC_NEAR                                    */ (100233, CONCAT(@T_CMD_INFO, 'Found %u creatures in %.3f yards.')),
/* FREEDOM_CMDI_NPC_NEAR_MAX_RESULT_COUNT                   */ (100234, CONCAT(@T_CMD_INFO, 'Found %u (Max result count) creatures in %.3f yards.')),
/* FREEDOM_CMDI_NPC_NEAR_LIST_ITEM                          */ (100235, '%.3f yards - Entry: %u : %s'),
/* FREEDOM_CMDI_CREATURE_MOVE                               */ (100236, CONCAT(@T_CMD_INFO, 'Creature %s (GUID: %llu) moved')),
/* FREEDOM_CMDI_CREATURE_TURNED                             */ (100237, CONCAT(@T_CMD_INFO, 'Creature %s (GUID: %llu) turned')),
/* FREEDOM_CMDH_NPC_SET_EMOTE                               */ (100238, CONCAT(@T_CMD_SYNTAX, '.npc set emote $emoteId [$guid]')),
/* FREEDOM_CMDI_NPC_SET_EMOTE                               */ (100239, CONCAT(@T_CMD_INFO, 'Creature emote set and saved')),
/* FREEDOM_CMDH_NPC_SET_MOUNT                               */ (100240, CONCAT(@T_CMD_SYNTAX, '.npc set mount $mountId [$guid]')),
/* FREEDOM_CMDI_NPC_SET_MOUNT                               */ (100241, CONCAT(@T_CMD_INFO, 'Creature mount set and saved')),
/* FREEDOM_CMDH_NPC_SET_AURA                                */ (100242, CONCAT(@T_CMD_SYNTAX, '.npc set aura $auraId on/off [$guid]')),
/* FREEDOM_CMDI_NPC_SET_AURA                                */ (100243, CONCAT(@T_CMD_INFO, 'Creature aura set and saved')),
/* FREEDOM_CMDH_NPC_SET_DEATHSTATE                          */ (100244, CONCAT(@T_CMD_SYNTAX, '.npc set deathstate on/off [$guid]')),
/* FREEDOM_CMDI_NPC_SET_DEATHSTATE                          */ (100245, CONCAT(@T_CMD_INFO, 'Creature animation state set/unset (death) and saved')),
/* FREEDOM_CMDH_NPC_SET_SLEEPSTATE                          */ (100246, CONCAT(@T_CMD_SYNTAX, '.npc set sleepstate on/off [$guid]')),
/* FREEDOM_CMDI_NPC_SET_SLEEPTSTATE                         */ (100247, CONCAT(@T_CMD_INFO, 'Creature animation state set/unset (sleep) and saved')),
/* FREEDOM_CMDH_NPC_SET_HOVERSTATE                          */ (100248, CONCAT(@T_CMD_SYNTAX, '.npc set hoverstate on/off [$guid]')),
/* FREEDOM_CMDI_NPC_SET_HOVERSTATE                          */ (100249, CONCAT(@T_CMD_INFO, 'Creature animation state set/unset (hover) and saved')),
/* FREEDOM_CMDH_NPC_PLAYEMOTE                               */ (100250, CONCAT(@T_CMD_SYNTAX, '.npc playemote $emoteId [$guid]')),
/* FREEDOM_CMDI_NPC_PLAYEMOTE                               */ (100251, CONCAT(@T_CMD_INFO, 'Creature temporary emote set')),
/* FREEDOM_CMDH_NPC_SET_MODEL                               */ (100252, CONCAT(@T_CMD_SYNTAX, '.npc set model $displayId [$guid]')),
/* FREEDOM_CMDI_NPC_SET_MODEL                               */ (100253, CONCAT(@T_CMD_INFO, 'Creature display set and saved')),
/* FREEDOM_CMDH_NPC_SAY                                     */ (100254, CONCAT(@T_CMD_SYNTAX, '.npc say $message')),
/* FREEDOM_CMDH_NPC_TEXTEMOTE                               */ (100255, CONCAT(@T_CMD_SYNTAX, '.npc textemote $message')),
/* FREEDOM_CMDH_NPC_WHISPER                                 */ (100256, CONCAT(@T_CMD_SYNTAX, '.npc whisper $playerName $message')),
/* FREEDOM_CMDH_NPC_YELL                                    */ (100257, CONCAT(@T_CMD_SYNTAX, '.npc yell $message')),
/* FREEDOM_CMDE_NPC_UNFOLLOW_NOT_A_FOLLOWER                 */ (100258, CONCAT(@T_CMD_ERROR, 'Targeted creature %s was not set to follow you')),
/* FREEDOM_CMDI_NPC_UNFOLLOW                                */ (100259, CONCAT(@T_CMD_INFO, 'Targeted creature %s is now no longer following you')),
/* FREEDOM_CMDE_FREEDOM_TAME_ALREADY_HAVE_PET               */ (100260, CONCAT(@T_CMD_ERROR, @C_TEXT, 'You already have a pet.', @C_CLOSE)),
/* FREEDOM_CMDE_FREEDOM_TAME_NOT_TAMEABLE                   */ (100261, CONCAT(@T_CMD_ERROR, @C_TEXT, 'Target pet is not tameable.', @C_CLOSE)),
/* FREEDOM_CMDI_FREEDOM_TAME                                */ (100262, CONCAT(@T_CMD_INFO, @C_TEXT, 'Pet %s successfully tamed.', @C_CLOSE)),
/* FREEDOM_CMDE_FREEDOM_TAME_ALREADY_A_PET                  */ (100263, CONCAT(@T_CMD_ERROR, @C_TEXT, 'Target is already a pet creature (you have to select creature, which is not a pet of someone else).', @C_CLOSE)),
/* FREEDOM_CMDE_ENTRY_X_NOT_EXIST_IN_TABLE_X                */ (100264, CONCAT(@T_CMD_ERROR, 'Entry %u does not exist in %s table. Contact developers about this!')),
/* FREEDOM_CMDH_LOOKUP_ITEM                                 */ (100265, CONCAT(@T_CMD_SYNTAX, '.lookup item [modifiers] $itemNamePart')),
/* FREEDOM_CMDE_INVALID_MODIFIER_ARG_FOR_MOD_X              */ (100266, CONCAT(@T_CMD_ERROR, 'Invalid modifier argument for: %s')),
/* FREEDOM_CMDE_MODIFIERS_CANNOT_BE_USED_TGTHR              */ (100267, CONCAT(@T_CMD_ERROR, 'Following modifiers cannot be used together: %s')),
/* FREEDOM_CMDI_LOOKUP_ITEM_NONE_FOUND                      */ (100268, CONCAT(@T_CMD_INFO, 'No items were found')),
/* FREEDOM_CMDI_LOOKUP_ITEM                                 */ (100269, CONCAT(@T_CMD_INFO, 'Found %llu items (%u is max result count a lookup can return)')),
/* FREEDOM_CMDI_FREEDOM_PANDAHORDE                          */ (100270, CONCAT(@T_CMD_INFO, 'You have set your faction as a Horde Pandaren successfully! Please, logout and log back in.')),
/* FREEDOM_CMDI_FREEDOM_PANDAALLIANCE                       */ (100271, CONCAT(@T_CMD_INFO, 'You have set your faction as an Alliance Pandaren successfully! Please, logout and log back in.')),
/* FREEDOM_CMDE_FREEDOM_PANDA_NOT_NEUTRAL                   */ (100272, CONCAT(@T_CMD_ERROR, 'This command can only be used by neutral pandaren')),
/* FREEDOM_CMDE_SERVICE_RESTRICTED_FOR_PANDAS               */ (100273, CONCAT(@T_CMD_ERROR, 'This command cannot be used by pandaren race')),
/* FREEDOM_CMDE_SERVICE_RESTRICTED_FOR_NPANDAS              */ (100274, CONCAT(@T_CMD_ERROR, 'This command cannot be used by neutral pandaren race')),
/* FREEDOM_CMDI_RELOAD_WORLD_DB                             */ (100275, CONCAT(@T_GLOBAL_GM, @C_TEXT, 'WorldDatabase table ', @C_LINK, '%s', @C_TEXT, ' has been reloaded.', @C_CLOSE)),
/* FREEDOM_CMDI_RELOAD_EXECUTOR                             */ (100276, CONCAT(@T_GLOBAL, @C_LINK, '.freedom reload %s', @C_TEXT, ' command has been triggered by %s', @C_TEXT, '.', @C_ERR, ' Server may pause/lag for a few moments.', @C_CLOSE)),
/* FREEDOM_CMDI_RELOAD_FINISH                               */ (100277, CONCAT(@T_GLOBAL, @C_TEXT, 'Reload finished in ', @C_LINK, '%u ms', @C_CLOSE)),
/* FREEDOM_CMDH_NPC_SET_BYTES1                              */ (100278, CONCAT(@T_CMD_SYNTAX, '.npc set bytes1 $bytes1 [$guid]')),
/* FREEDOM_CMDH_NPC_SET_BYTES2                              */ (100279, CONCAT(@T_CMD_SYNTAX, '.npc set bytes2 $bytes2 [$guid]')),
/* FREEDOM_CMDI_NPC_SET_BYTES1                              */ (100280, CONCAT(@T_CMD_INFO, 'Creature UNIT_FIELD_BYTES_1 set')),
/* FREEDOM_CMDI_NPC_SET_BYTES2                              */ (100281, CONCAT(@T_CMD_INFO, 'Creature UNIT_FIELD_BYTES_2 set')),
/* FREEDOM_CMDH_NPC_SET_SITGROUNDSTATE                      */ (100282, CONCAT(@T_CMD_SYNTAX, '.npc set sitgroundstate on/off [$guid]')),
/* FREEDOM_CMDI_NPC_SET_SITGROUNDSTATE                      */ (100283, CONCAT(@T_CMD_INFO, 'Creature animation state set/unset (sit on ground) and saved')),
/* FREEDOM_CMDH_NPC_SET_SITLOWSTATE                         */ (100284, CONCAT(@T_CMD_SYNTAX, '.npc set sitlowstate on/off [$guid]')),
/* FREEDOM_CMDI_NPC_SET_SITLOWSTATE                         */ (100285, CONCAT(@T_CMD_INFO, 'Creature animation state set/unset (sit on low height) and saved')),
/* FREEDOM_CMDH_NPC_SET_SITMEDIUMSTATE                      */ (100286, CONCAT(@T_CMD_SYNTAX, '.npc set sitmediumstate on/off [$guid]')),
/* FREEDOM_CMDI_NPC_SET_SITMEDIUMSTATE                      */ (100287, CONCAT(@T_CMD_INFO, 'Creature animation state set/unset (sit on medium height) and saved')),
/* FREEDOM_CMDH_NPC_SET_SITHIGHSTATE                        */ (100288, CONCAT(@T_CMD_SYNTAX, '.npc set sithighstate on/off [$guid]')),
/* FREEDOM_CMDI_NPC_SET_SITHIGHSTATE                        */ (100289, CONCAT(@T_CMD_INFO, 'Creature animation state set/unset (sit on high height) and saved')),
/* FREEDOM_CMDH_NPC_SET_KNEELSTATE                          */ (100290, CONCAT(@T_CMD_SYNTAX, '.npc set kneelstate on/off [$guid]')),
/* FREEDOM_CMDI_NPC_SET_KNEELSTATE                          */ (100291, CONCAT(@T_CMD_INFO, 'Creature animation state set/unset (kneel) and saved')),
/* FREEDOM_CMDH_NPC_SET_SHEATHSTATE                         */ (100292, CONCAT(@T_CMD_SYNTAX, '.npc set sheathstate 0/1/2 [$guid]')),
/* FREEDOM_CMDI_NPC_SET_SHEATHSTATE                         */ (100293, CONCAT(@T_CMD_INFO, 'Creature sheath state set/unset and saved')),
/* FREEDOM_CMDH_NPC_SET_GRAVITY                             */ (100294, CONCAT(@T_CMD_SYNTAX, '.npc set gravity on/off [$guid]')),
/* FREEDOM_CMDI_NPC_SET_GRAVITY                             */ (100295, CONCAT(@T_CMD_INFO, 'Creature gravity toggle set/unset and saved')),
/* FREEDOM_CMDH_NPC_SET_SWIM                                */ (100296, CONCAT(@T_CMD_SYNTAX, '.npc set swim on/off [$guid]')),
/* FREEDOM_CMDI_NPC_SET_SWIM                                */ (100297, CONCAT(@T_CMD_INFO, 'Creature swim toggle set/unset and saved')),
/* FREEDOM_CMDH_FREEDOM_TITLE_SET                           */ (100298, CONCAT(@T_CMD_SYNTAX, '.freedom title set $titleId')),
/* FREEDOM_CMDE_FREEDOM_TITLE_SET_INVALID_TITLEID           */ (100299, CONCAT(@T_CMD_ERROR, 'Specified title with ID %u does not exist')),
/* FREEDOM_CMDI_FREEDOM_TITLE_LIST_ITEM                     */ (100300, '%u - %s'),
/* FREEDOM_CMDI_FREEDOM_TITLE_LIST_NONE_FOUND               */ (100301, CONCAT(@T_CMD_INFO, 'No titles were found')),
/* FREEDOM_CMDI_FREEDOM_TITLE_LIST                          */ (100302, CONCAT(@T_CMD_INFO, 'Found %u titles')),
/* FREEDOM_CMDI_FREEDOM_TITLE_SET                           */ (100303, CONCAT(@T_CMD_INFO, 'Title set to ID: %u, MaskID: %u, Title format: %s')),
/* FREEDOM_CMDI_FREEDOM_TITLE_SET_UNSET                     */ (100304, CONCAT(@T_CMD_INFO, 'Title toggled off')),
/* FREEDOM_CMDH_NPC_SET_FLYSTATE                            */ (100305, CONCAT(@T_CMD_SYNTAX, '.npc set flystate on/off [$guid]')),
/* FREEDOM_CMDI_NPC_SET_FLYSTATE                            */ (100306, CONCAT(@T_CMD_INFO, 'Creature animation state set/unset (flying or swimming in air) and saved')),
/* FREEDOM_CMDI_PINFO_START                                 */ (100307, CONCAT(@T_CMD_INFO, 'Listing information for player %s (DB GUID: %u):')),
/* FREEDOM_CMDI_PINFO_GAME_ACCOUNT                          */ (100308, '> Game-Account: %s (ID: %u) (GMLevel: %u)'),
/* FREEDOM_CMDI_PINFO_BNET_ACCOUNT                          */ (100309, '> Bnet-Account: %s (ID: %u)'),
/* FREEDOM_CMDI_PINFO_IP                                    */ (100310, '> IP: %s (Locked: %s)'),
/* FREEDOM_CMDI_PINFO_EMAIL                                 */ (100311, '> Email: %s, RegEmail: %s'),
/* FREEDOM_CMDI_PINFO_LAST_LOGIN                            */ (100312, '> Last login: %s (Failed logins: %u)'),
/* FREEDOM_CMDI_PINFO_ONLINE                                */ (100313, '> Online?: %s'),
/* FREEDOM_CMDI_PINFO_ALIVE                                 */ (100314, '> Alive?: %s'),
/* FREEDOM_CMDI_PINFO_GM_TOGGLE                             */ (100315, '> GM toggle: %s'),
/* FREEDOM_CMDI_PINFO_BANNED                                */ (100316, '> Banned?: %s'),
/* FREEDOM_CMDI_PINFO_PLAYED_TIME                           */ (100317, '> Total Playtime: %s'),
/* FREEDOM_CMDI_PINFO_RACE                                  */ (100318, '> Race: %s %s'),
/* FREEDOM_CMDI_PINFO_CLASS                                 */ (100319, '> Class: %s'),
/* FREEDOM_CMDI_PINFO_MAP                                   */ (100320, '> Map: %s, Zone: %s, Area: %s'),
/* FREEDOM_CMDI_PINFO_PHASEMASK                             */ (100321, '> Phasemask: %u'),
/* FREEDOM_CMDI_PINFO_GUILD                                 */ (100322, '> Guild: %s (ID: %u) (Rank: %s [Id: %u])'),
/* FREEDOM_CMDI_PINFO_GUILD_NOTE                            */ (100323, '> Guild note: %s'),
/* FREEDOM_CMDI_PINFO_GUILD_OFFICER_NOTE                    */ (100324, '> Guild officer note: %s'),
/* FREEDOM_CMDI_PINFO_PHASEMASK_GM_ON                       */ (100325, '> Phasemask: (in all phases due to GM toggled to \'on\')'),
/* FREEDOM_CMDI_PINFO_BAN_INFO                              */ (100326, '> Ban info:'),
/* FREEDOM_CMDI_PINFO_BAN_INFO_LI_REASON                    */ (100327, '    Reason: %s'),
/* FREEDOM_CMDI_PINFO_BAN_INFO_LI_LENGTH                    */ (100328, '    Length: %s'),
/* FREEDOM_CMDI_PINFO_BAN_INFO_LI_BANNED_BY                 */ (100329, '    Banned by: %s'),
/* FREEDOM_CMDI_PINFO_BAN_INFO_LI_TYPE                      */ (100330, '    Type: %s'),
/* FREEDOM_CMDI_PINFO_MUTE_INFO                             */ (100331, '> Mute info:'),
/* FREEDOM_CMDI_PINFO_MUTE_INFO_LI_REASON                   */ (100332, '    Reason: %s'),
/* FREEDOM_CMDI_PINFO_MUTE_INFO_LI_LENGTH                   */ (100333, '    Length: %s'),
/* FREEDOM_CMDI_PINFO_MUTE_INFO_LI_BANNED_BY                */ (100334, '    Muted by: %s'),
/* FREEDOM_CMDH_FREEDOM_GUILD_CREATE                        */ (100335, CONCAT(@T_CMD_SYNTAX, '.freedom guild create $guildName')),
/* FREEDOM_CMDI_FREEDOM_GUILD_CREATE                        */ (100336, CONCAT(@T_CMD_INFO, 'Guild successfully created with you as leader: %s')),
/* FREEDOM_CMDE_FREEDOM_GUILD_CREATE_ALREADY_IN             */ (100337, CONCAT(@T_CMD_ERROR, 'You are already in a guild')),
/* FREEDOM_CMDE_FREEDOM_GUILD_CREATE_FAILED                 */ (100338, CONCAT(@T_CMD_ERROR, 'Guild creation failed (does the guild already exist?)')),
/* FREEDOM_CMDH_GOBJECT_AXIAL                               */ (100339, CONCAT(@T_CMD_SYNTAX, '.gobject axial $roll $pitch $yaw [$guid]')),
/* FREEDOM_CMDI_GOBJECT_AXIAL                               */ (100340, CONCAT(@T_CMD_INFO, 'Gameobject axial rotation set to (ROLL: %.2f°, PITCH: %.2f°, YAW: %.2f°)')),
/* FREEDOM_CMDH_GOBJECT_ROLL                                */ (100341, CONCAT(@T_CMD_SYNTAX, '.gobject roll [modifiers] $roll [$guid]')),
/* FREEDOM_CMDI_GOBJECT_ROLL                                */ (100342, CONCAT(@T_CMD_INFO, 'Gameobject ROLL rotation set to %.2f°')),
/* FREEDOM_CMDH_GOBJECT_PITCH                               */ (100343, CONCAT(@T_CMD_SYNTAX, '.gobject pitch [modifiers] $pitch [$guid]')),
/* FREEDOM_CMDI_GOBJECT_PITCH                               */ (100344, CONCAT(@T_CMD_INFO, 'Gameobject PITCH rotation set to %.2f°')),
/* FREEDOM_CMDH_GOBJECT_YAW                                 */ (100345, CONCAT(@T_CMD_SYNTAX, '.gobject yaw [modifiers] $yaw [$guid]')),
/* FREEDOM_CMDI_GOBJECT_YAW                                 */ (100346, CONCAT(@T_CMD_INFO, 'Gameobject YAW rotation set to %.2f°')),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_ROLL                     */ (100347, '> Roll: %.6f (Deg: %.2f°)'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_PITCH                    */ (100348, '> Pitch: %.6f (Deg: %.2f°)'),
/* FREEDOM_CMDI_GAMEOBJECT_INFO_LI_YAW                      */ (100349, '> Yaw: %.6f (Deg: %.2f°)'),
/* FREEDOM_CMDI_ADDITEM_ALL                                 */ (100350, CONCAT(@T_CMD_INFO, 'Mass-added itemID = %i, amount = %i')),
/* FREEDOM_CMDI_REMOVEITEM_ALL                              */ (100351, CONCAT(@T_CMD_INFO, 'Mass-removed itemID = %i, amount = %i')),
/* FREEDOM_CMDI_PLAYED_LOCALLY                              */ (100352, CONCAT(@T_CMD_INFO, 'Sound %u played to nearby (in sight) players.')),
/* FREEDOM_CMDE_GAMEOBJECT_SPAWN_INVALID_DISPLAY_C          */ (100353, CONCAT(@T_CMD_ERROR, 'Encountered error when trying to spawn gameobject with entry %u (Invalid display: cannot find display with id %u), but still attempting to spawn! Contact developers about this!')),
/* FREEDOM_CMDI_TOBEREADDED                                 */ (100354, CONCAT(@T_CMD_INFO, 'Changed your model to: %u')),
/* FREEDOM_CMDH_TOBEREADDED                                 */ (100355, CONCAT(@T_CMD_SYNTAX, '.npc set dynflags $dynflags [$guid]')),
/* FREEDOM_CMDI_TOBEREADDED                                 */ (100356, CONCAT(@T_CMD_INFO, 'Creature OBJECT_DYNAMIC_FLAGS set')),
/* FREEDOM_CMDH_TOBEREADDED                                 */ (100357, CONCAT(@T_CMD_SYNTAX, '.npc set unitflags $unitflags [$guid]')),
/* FREEDOM_CMDI_TOBEREADDED                                 */ (100358, CONCAT(@T_CMD_INFO, 'Creature UNIT_FIELD_FLAGS set')),
/* FREEDOM_CMDE_ACCT_INDEX_NO_MATCH                         */ (100359, CONCAT(@T_CMD_ERROR, 'Value entered does not match total amount of game accounts you currently have!  This check is simply for you to acknowledge how many accounts you have and to consider whether another account is necessary (especially if you already have many of them!).')),
/* FREEDOM_CMDH_GAMEACCOUNTCREATE                           */ (100360, CONCAT(@T_CMD_INFO, '.freedom gameaccount $currentamountofgameaccounts $randompassword\r\nThis command will create another game account for you to use that will be associated with your main BattleNet account.\r\n$currentamountofgameaccounts is just for you to acknowledge how many game accounts you have currently (and to also help ensure you do not \'accidentally\' keep creating more game accounts).\r\n$randompassword is just a random password (not actually used to log in) to generate the account.  Must be less than 16 characters.')),
/* FREEDOM_CMDI_CREATURE_INFO_PHASESHIFT                    */ (100361, '> PhaseID: %u, PhaseGroup: %u'),
/* FREEDOM_CMDH_ACCOUNTACCESS                               */ (100362, CONCAT(@T_CMD_INFO, '.freedom accountaccess 1\r\nThis command will set your access level to that of your main (first) game account.  This is only useful when using this command on an additional game account.')),
/* FREEDOM_CMDE_ACCOUNTACCESS_SAMELEVEL                     */ (100363, CONCAT(@T_CMD_ERROR, 'Your account access level is already the same as your main account!')),
/* FREEDOM_CMDE_ACCOUNTACCESS_CONFIRM                       */ (100364, CONCAT(@T_CMD_ERROR, 'Be sure to type a 1 after the accountaccess command (this is just to ensure you read the command info).')),
/* FREEDOM_CMDI_ACCOUNTACCESS_DONE                          */ (100365, CONCAT(@T_CMD_INFO, 'Account access updated!')),
/* FREEDOM_CMDH_CHANGEACCOUNT                               */ (100366, CONCAT(@T_CMD_SYNTAX, '.freedom changeaccount $character $account\n\nTransfers named character from one game account to another on your BNet account.  When designating target account, use just the number (first account = 1, second = 2, etc)')),
/* FREEDOM_CMDE_CHANGEACCOUNT_DIFFBNETACCT                  */ (100367, CONCAT(@T_CMD_ERROR, 'Either the character is not on your BNet account or the destination game account is not yours!  Please check the spelling of the given character name.')),

(200000, 'Dummy');
