CREATE TABLE IF NOT EXISTS `npc_to_itemid` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`creatureid` INT UNSIGNED NOT NULL DEFAULT '0',
	`creaturename` MEDIUMTEXT NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci',
	`itemid` MEDIUMINT UNSIGNED NOT NULL,
	`itemappearancemodifierid` TINYINT UNSIGNED NOT NULL
);
