CREATE TABLE `tickets` (
	`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`id_bnet_acc` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`id_player` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
	`id_bnet_acc_assignee` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`id_player_assignee` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
	`content` TEXT NOT NULL,
	`status` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
	`created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`closed` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`id_bnet_acc_closedby` INT(10) UNSIGNED NOT NULL DEFAULT '0',
	`id_player_closedby` BIGINT(20) UNSIGNED NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;