ALTER TABLE `creature_extra`
	ADD COLUMN `swim` TINYINT UNSIGNED NOT NULL DEFAULT '1' AFTER `gender`,
	ADD COLUMN `gravity` TINYINT UNSIGNED NOT NULL DEFAULT '1' AFTER `swim`,
	ADD COLUMN `fly` TINYINT UNSIGNED NOT NULL DEFAULT '0' AFTER `gravity`;
