-- Database creation script for WoW Freedom

DROP DATABASE IF EXISTS `freedom`;
CREATE DATABASE IF NOT EXISTS `freedom` /*!40100 DEFAULT CHARACTER SET utf8 */;

DROP DATABASE IF EXISTS `wod_auth`;
CREATE DATABASE IF NOT EXISTS `wod_auth` /*!40100 DEFAULT CHARACTER SET utf8 */;

DROP DATABASE IF EXISTS `wod_characters`;
CREATE DATABASE IF NOT EXISTS `wod_characters` /*!40100 DEFAULT CHARACTER SET utf8 */;

DROP DATABASE IF EXISTS `wod_hotfixes`;
CREATE DATABASE IF NOT EXISTS `wod_hotfixes` /*!40100 DEFAULT CHARACTER SET utf8 */;

DROP DATABASE IF EXISTS `wod_world`;
CREATE DATABASE IF NOT EXISTS `wod_world` /*!40100 DEFAULT CHARACTER SET utf8 */;
